name:                hrenamer
version:             0.1.0.0
github:              "phurtado/hrenamer"
license:             BSD3
author:              "Pablo Hurtado"
maintainer:          "hurtado.pani@gmail.com"
copyright:           "2019 Pablo Hurtado"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/phurtado/hrenamer#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- text
- parsec
- optparse-applicative

library:
  source-dirs: src

executables:
  hrenamer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hrenamer

tests:
  hrenamer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hrenamer
